### ISSUE TITLE
serve report.html and option to disable append to report

### ISSUE THREAD

**Issue by Shawful** [Nemesarial/karma-dhtml-reporter#2]
Hello,

I am trying to serve up the report.html that is generated after running "karma start" when singleRun: true.

I've tried using 

files: [
      {
        pattern:'/test/report.html',
        watched: true, 
        included: false, 
        served: true
      }
    ],

within karma.conf.js, but without any luck when checking http://localhost/base/test/report.html.

Also, I have noticed that when I have singleRun: false and files are being monitored, this tool appends to the report.html, which can lead to false information.  Is there an option to programatically clear any previous report.html and then re-generate it?

**Comment by mholtzhausen** [comment]
Thanks for the feedback. I will take a look and get back to you @Shawful

**Comment by Shawful** [comment]
In the mean time, I have swapped back to a command line report, but I will definitely want this in the future.

**Comment by mholtzhausen** [comment]
@Shawful I added an option to have the report opened in the browser,  and I have fixed the duplicate output.
