### ISSUE TITLE
No provider for "framework:mocha"

### ISSUE THREAD

**Issue by preflight** [Nemesarial/karma-dhtml-reporter#5]
Your reporter looks really great. Trying to get it configured, but am running into an issue anytime I run my specs with karma-dhtml-reporter enabled in `karma.conf.js`.

The error/warning is `Warning: No provider for "framework:mocha"! (Resolving: framework:mocha)`

My tests are running without issue when the reporter isn't enabled. Here are the versions I'm using:
- karma: 0.12.31
- grunt: 0.4.5
- grunt-karma: 0.10.1
- mocha: 2.2.1
- karma-mocha: 0.1.10
- karma-dhtml-reporter: 0.2.5

(In case it's relevant, I'm also using Chai, Sinon, Chai-jQuery, Sinon-Chai, and Browserify)

And I'm using the config prescribed in your docs. See anything I'm doing wrong?

```
reporters: ['progress', 'DHTML'],
plugins: ['karma-dhtml-reporter'],
dhtmlReporter: {
  outputFile: 'spec.html'
}
```

Thanks!

**Comment by preflight** [comment]
Update: I got it basically working by commenting out the `plugins: ['karma-dhtml-reporter']` option. A couple issues remain in case you want to take a look:
- The `outputFile` is in the correct directory but is named `_testspec.html` (not a big deal)
- The reporter isn't recognizing the Mocha convention `xit()` for ignoring tests. Also not a huge deal, but would be nice to fix if you happen to know what's causing that one.

Thanks again - I'll leave this open for a bit in case you want to look into that second item

**Comment by mholtzhausen** [comment]
Thanx @michael-jarosik . I'll take a look when I have a spot of time.

**Comment by preflight** [comment]
Thanks - closing the issue since the plugin works despite those two quirks. Feel free to reopen if you prefer.
