### ISSUE TITLE
404 error when installing karma-dhtml-reporter due to semantics-ui dependency

### ISSUE THREAD

**Issue by yostwal** [Nemesarial/karma-dhtml-reporter#8]
The dependency `"semantic-ui": "^1.8.1"` causes the following error 
`error An unexpected error occurred: "https://github.com/derekslife/wrench-js/tarball/156eaceed68ed31ffe2a3ecfbcb2be6ed1417fb2: Request failed \"404 Not Found\"".`

On doing a little research, I found that dereksfile no longer exists on github.

**Comment by yostwal** [comment]
Further research - In [semantic-ui v2.2.8](https://github.com/Semantic-Org/Semantic-UI/blob/2c3511b99c420ae16ff844b9f2b1094a01568b96/RELEASE-NOTES.md#user-content-version-228---february-21-2017), semantic-org has updated **build tools** with the following comment: 

> Removed dependency on tarball, packaged new patched WrenchJS under Semantic-org

**Comment by mholtzhausen** [comment]
Pardon the delay @yostwal -- This issue is dated, and I assume fixed. I'll close for now.
